language: node_js
node_js:
- 11.10.1
dist: trusty
sudo: false
deploy:
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: PuX/VCDTOb0GU+jC+osdbbzFrt34HQ3OscwgupD0xx0dc5h5AOmXLSsDTLFZh5Kp9khcCScuIFCKqL0Z+lez+nt5fsen9q3Mc5fTQkqF0f9YMacJI78mQhI/0wm7eDeWgw7fGca6y9ucEI2/CmRc+ClVajO3GDMlllmkRek5S6t/lB+vsm9K8mDB6wEgfPaxjhbazIP9ToKpVPQQ0LwZymrFpkb5x43femHwGqzBI6F5PV7ExR13pjPN9thgWLXfAS7J+kVu1oljMXo3Dg3l0kKsp5iHcVejerCElE55g0CWStwfc5X9mFNGrE6cEzn4J2fCM2IX0U1HfbFXbdkDijJlLVoA8fTkwqGjQl7YozVyEHuTrsUoSrxdu7Y8IJZCe6izWysdqYp1ZxU/g2X+62/brHAqHpYlKTvh1SrHnFh5wYl+0jlEMUfBPb8Gtj8T99k3ATL1LhGMJKggRIN8pAmBpsLq651z3coDDGy+rcViM1KVwG25oLd9Fun1R1UwWGbUK2NoQ4SmQZxVwIMHFDwQb4ODZ9iCuAYgLA/t08H63LxVmktH8SQkrKrkBgkk7mR37xR+EIhPKt1A5X4plINeSNCGa6gw1TTN2xqr8aP3pUbwMMFYm5/E6yOYkb+Cqc9a2P334bOS0KOoCeHMuUDu/vO6vzdz1p7d/mL9T4g=
  - secure: ksnYRulrIve/aCPNTwqwzwRiGq2FAQTi+1xKUqb18QKrymgA7tEbocBwgXbQFiBCrlqt73t/+ia7wVhWC98Xx0ACcUvo7OLgu2tQuYia1KnMfveT8wPe0DRmEnBiJnijXDECcf0UtkXIVT33cN9K3+xkOCZlJpMUDyBnM52n6AYo7RDM2B/V/JXyNt2knoay6uuadvyQti9NkD58BmP6JdbRomT5CLE3Uf+mDnnvd7Zw+FbrXjsfLwdLFN8ljc9tMWvEZLqrz3fBnPw8gdTLhjLZoafsbhTtntcrQOa07tTDBpiIBf2P1K3Q2efoGLOy6EgNjfvFFJekd3BI5FDwmWuXgoCfngy42L9TAxG0asRptZVeZTA1XZEuP/iQAQz5ELjHIBXpmAErHfAv7Fu9eRMQ+LzA1wEIBsSEo+CaYgwCFr4u7/4SA09prNz/cepXgedaTJ+DQvgcH+GLJh/ccSZ4RdJU3nG2QBDgkFvXDl9KAzoTYrlYsF6sh6juITg9zG3DMfbPENSNZh4V2BJIeiPHGLsZSjf68Domre1F/Qjyx38O3qo6GebEX/YfFInfyq16HCeBYRr1Y1cagXu4rly+vDZ06AeqInj9trmpM2c2cYu+0Uy20saGAuTHLiv2uQk29Set+/JXmfSgDeEn8PR0aVP6QgBqtWajy71XkuE=
after_success:
  - curl -T index.html -u $FTP_USER:$FTP_PASSWORD ftp://gaardbodigital.dk/public_html
artifacts:
  - public/**
